version: '3.3'

services:
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: neotech
            MYSQL_DATABASE: neotech
            MYSQL_USER: neotech
            MYSQL_PASSWORD: neotech
        ports:
            - 3307:3306